resource "aws_db_instance" "postgresql" {
  allocated_storage                         = var.db_allocated_storage
  engine                                    = var.db_engine
  engine_version                            = var.db_engine_version
  instance_class                            = var.db_instance_class
  backup_retention_period                   = 7
  backup_window                             = "18:00-18:30"
  ca_cert_identifier                        = "rds-ca-2019"
  character_set_name                        = null
  copy_tags_to_snapshot                     = true
  customer_owned_ip_enabled                 = false
  db_subnet_group_name                      = var.db_subnet_group_name
  deletion_protection                       = var.db_deletion_protection
  enabled_cloudwatch_logs_exports           = var.enabled_cloudwatch_logs_exports
  iam_database_authentication_enabled       = var.iam_database_authentication_enabled
  identifier                                = var.db_identifier
  identifier_prefix                         = null
  iops                                      = 0
  # kms_key_id                                = var.db_kms_key_id
  kms_key_id                                = aws_kms_key.rds_kms.arn
  license_model                             = var.db_license_model
  maintenance_window                        = "sun:19:00-sun:19:30"
  master_user_secret_kms_key_id             = null
  max_allocated_storage                     = var.db_max_allocated_storage
  # monitoring_role_arn                       = var.db_monitoring_role_arn
  monitoring_role_arn                       = aws_iam_role.rds_monitoring_role.arn
  multi_az                                  = var.multi_az
  nchar_character_set_name                  = null
  network_type                              = "IPV4"
  option_group_name                         = "default:postgres-14"
  parameter_group_name                      = "default.postgres14"
  # performance_insights_kms_key_id           = var.db_performance_insights_kms_key_id
  performance_insights_kms_key_id           = aws_kms_key.rds_kms.arn
  performance_insights_retention_period     = 0
  port                                      = 5432
  replica_mode                              = null
  skip_final_snapshot                       = var.skip_final_snapshot
  snapshot_identifier                       = null
  storage_encrypted                         = true
  storage_throughput                        = 0
  storage_type                              = "gp2"
  tags                                      = var.db_tags
  tags_all                                  = var.db_tags
  timezone                                  = null
  username                                  = var.db_user_name
  vpc_security_group_ids                    = [aws_security_group.this.id]
}