# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sarvm-terraform-remote-backend"
    dynamodb_table = "sarvm-terraform-state-lock"
    encrypt        = true
    key            = "uat/elb/terraform.tfstate"
    profile        = "sarvm"
    region         = "ap-south-1"
  }
}
